### PR TITLE
navbar component added

### PR DESCRIPTION
**Pull request by vaibhav18matere**
fixed navbar, scrolling navbar, and navbar with drawer component added
Check for preview: https://deploy-preview-13--falconui.netlify.app/components/navbar/navbar

### CODE REVIEW

**Review by prathmeshjagtap — APPROVED** [review]

**Review by pariyar07 — COMMENTED** [review]
Looks good to me.

**Review by manojasarsa — APPROVED** [review]
LGTM!! 👍

**Review by pariyar07 — APPROVED** [review]
Good to go.

**Comment by vaibhav18matere** [comment]
> Looks good to me.

thanks!

**Pull request merged**
