### PR TITLE
text-utlities added

### PR DESCRIPTION
**Pull request by vaibhav18matere**
Heading, small text, grey text, centered text, alignment text and highlight text added
Check preview here : https://deploy-preview-9--falconui.netlify.app

### CODE REVIEW

**Review by anshikaa12 — APPROVED** [review]
code looks clean and good to merge!

**Comment by vaibhav18matere** [comment]
> code looks clean and good to merge!

Thanks!

**Review by manojasarsa — APPROVED** [review]
LGTM! 👍

**Comment by vaibhav18matere** [comment]
> LGTM! 👍

Thanks !

**Pull request merged**
